---
- hosts: windows 
  tasks:
  - name: stop 
    raw: "net stop couchbaseserver"
    ignore_errors: true
  - name: kill msiex 
    raw: " taskkill /F /T /IM msiexec32.exe" 
    ignore_errors: true
  - name: stop install 
    raw: "cmd /c schtasks /end /tn installme" 
  - name: stop removes 
    raw: "cmd /c schtasks /end /tn removeme" 
  - name: stop upgrades 
    raw: "cmd /c schtasks /end /tn upgrademe" 
  - name: kill sherlock 
    raw: "taskkill /F /T /IM {{ver_no}}-*" 
    ignore_errors: true
  - name: kill erlc 
    raw: "taskkill /F /T /IM erl*" 
    ignore_errors: true
  - name: kill epmd 
    raw: "taskkill /F /T /IM  epmd.exe*" 
    ignore_errors: true
  - name: kill cbq 
    raw: "taskkill /F /T /IM cbq-engine.exe" 
    ignore_errors: true
  - name: kill setup 
    raw: "taskkill /F /T /IM setup.exe" 
    ignore_errors: true
  - name: kill chrome 
    raw: "taskkill /F /T /IM chrome.exe" 
    ignore_errors: true
  - name: kill bash 
    raw: "taskkill /F /T /IM bash.exe" 
    ignore_errors: true
  - name: kill Wer 
    raw: "taskkill /F /T /IM WerFault.*" 
    ignore_errors: true
  - name: firewall off 
    raw: "netsh advfirewall set publicprofile state off" 
    ignore_errors: true

  - name: check version
    raw: 'type "C:\Program Files\Couchbase\Server\VERSION.txt"'
    register: chk_version
    ignore_errors: True
  - debug: 
      msg: "C:\\tmp\\{{chk_version.stdout_lines[0]}}.msi"
    when: chk_version.rc == 0
  - name: uninstall 
    win_msi:
      path: "C:\\tmp\\{{chk_version.stdout_lines[0]}}.msi"
      state: absent
      wait: true
    when: chk_version.rc == 0
  - name:  clean data 
    win_file: path="D:/data" state=absent
    ignore_errors: true
  - name:  mkdata
    win_file: path="C:/tmp" state=directory
    ignore_errors: true
  - name:  clean  tmp
    win_file: path="C:/tmp/" state=absent
  - name:  mktmp
    win_file: path="C:/tmp" state=directory
  - name: kill epmd 
    raw: "taskkill /F /T /IM  epmd.exe*" 
    ignore_errors: true
  - name: kill memcached 
    raw: "taskkill /F /T /IM memcac*" 
    ignore_errors: true
  - name: kill winrm 
    raw: "taskkill /F /T /IM winrshost.exe" 
    ignore_errors: true

